easy_admin:
  site_name: '<img src="%brand_logo%" style="max-width: 150px;" />'
  show: true

  entities:
    student:
      class: App\Entity\Student
      form:
        fields: ["firstname","lastname","promotion"]
      list:
        fields: ["firstname","lastname","promotion"]
      search:
        fields: ['lastname','firstname', 'promotion.name', 'promotion.year']
    teacher:
      class: App\Entity\Teacher
      form:
        fields: ["firstname","lastname"]
      list:
        fields: ["firstname","lastname"]
      search:
        fields: ['lastname','firstname', 'courses.name', 'courses.promotion.name']


    promotion:
      class: App\Entity\Promotion
      form:
        fields: ["name","year","students"]
      list:
        fields: ["name","year","students"]
      search:
        fields: ['name','year', 'students.lastname', 'students.firstname','courses.name','courses.teacher.firstname','courses.teacher.lastname']


    course:
      class: App\Entity\Course
      form:
        fields: ["name","startAt","endAt","teacher","promotion"]
      list:
        fields: ["name","startAt","endAt","teacher","promotion"]
        actions: ['Link']
        sort: 'startAt'
      search:
          # use an array to also define the sorting direction
        sort: ['startAt', 'ASC']
        fields: ['name','teacher.firstname', 'teacher.lastname', 'promotion.name','promotion.year','promotion.students.firstname','promotion.students.lastname']
